### ISSUE TITLE
Duplicated result

### ISSUE THREAD

**Issue by fvictorio** [suchipi/grep-ast#3]
Create a file with this content:

```
const { Foo } = require('foo')
```

and run `grep-ast 'Identifier[name="Foo"]'`

The output has two duplicated positions:

```
foo.js:1:8-1:11
foo.js:1:8-1:11
```

Not sure if the problem is in `grep-ast` or upstream, though.

**Comment by fvictorio** [comment]
Btw, this doesn't happen with `const Foo = require('foo')`

**Comment by suchipi** [comment]
This is kind of a quirk of the AST format. 
```
const { Foo } = require('foo')
```
is shorthand for this:
```
const { Foo: Foo } = require('foo')
```

and the AST actually represents both more or less the same, with just an added `shorthand: true` in the first case.

You can see this if you paste the code into https://astexplorer.net/ and select `babylon7` as the parser (same parser grep-ast uses by default).

**Comment by fvictorio** [comment]
I see, thanks!
